
{
    'name': 'GVP Students Admission',
    'version': '12.0.1.0.0',
    'author': 'Gujarat Vidyapith, Sadra',
    'website': 'http://www.gujaratvidyapith.org',
    'category': 'Students Management',
    'Summary': 'A Module For Students Management',
    'depends': ['hr', 'crm', 'account'],
    'data': ['security/school_security.xml',
             'security/ir.model.access.csv',
             'wizard/terminate_reason_view.xml',
             'wizard/wiz_send_email_view.xml',
             'views/student_view.xml',
             'views/school_view.xml',
             'views/hr_employee_view.xml',
             'views/company_view.xml',
             'data/student_sequence.xml',
             'wizard/move_semester_view.xml',
             'report/report_view.xml',
             'report/identity_card.xml',
             'views/template_view.xml',
             'views/subject_paper_view.xml',
             'views/time_table_view.xml',
             'wizard/import_student_view.xml',
             'wizard/import_student_log_view.xml',
             ],
    'demo': ['demo/school_demo.xml'],
    'installable': True,
    'application': True
}
